# Khử nhiễu
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3

# BLE
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_BT_BUF_ACL_RX_SIZE=512
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

# OLED
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Power management
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Wake up
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_USB=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# Logging off
CONFIG_ZMK_USB_LOGGING=n

# Mouse
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
